parameters:
  - name: azureSubscription
    type: string
  - name: aksResourceGroupName
    type: string
  - name: aksClusterName
    type: string
  - name: namespace
    type: string
  - name: releaseName
    type: string
  - name: taskName
    type: string
    default: 'helmStatus'

steps:
  - task: AzureCLI@2
    displayName: ${{ parameters.releaseName }} Helm Status
    name: ${{ parameters.taskName }}
    inputs:
      azureSubscription: '${{ parameters.azureSubscription }}'
      scriptType: 'pscore'
      scriptLocation: 'inlineScript'
      inlineScript: |
        $namespace="$($env:namespace)"
        $releaseName="$($env:releaseName)"

        $aksClusterName="$($env:aksClusterName)"
        $aksResourceGroupName="$($env:aksResourceGroupName)"

        az aks get-credentials --name $aksClusterName --resource-group $aksResourceGroupName --overwrite-existing -a

        Write-Host "##[section]Looking for HELM Release '$releaseName'."
        
        $releases = $(helm list --namespace $namespace -o json | ConvertFrom-Json) | Where-Object {$_.name -eq $releaseName}

        $statusResult = ""
        $exists = $true
        if ($releases.length -lt 1) {
            $statusResult = "Release does not exist"
            $exists = $false
            Write-host $statusResult
        }
        else {
            $releaseStatus = helm status -n $namespace $releaseName -o json | ConvertFrom-Json
            Write-host "Release Exists"
            Write-host "Name: $($releaseStatus.name)"
            Write-host "Status: $($releaseStatus.info.status)"
            #Write-host "Note: $($releaseStatus.info.notes)"
            $statusResult = "$($releaseStatus.info.status)"
        }
        Write-Host "##vso[task.setvariable variable=status;isOutput=true]$statusResult"
        Write-Host "##vso[task.setvariable variable=exists;isOutput=true]$exists"

    env:
      releaseName: ${{ parameters.releaseName }}
      namespace: ${{ parameters.namespace }}
      aksResourceGroupName: ${{ parameters.aksResourceGroupName }}
      aksClusterName: ${{ parameters.aksClusterName }}