parameters:
  - name: azureSubscription
    type: string
    default: ""
  - name: kubernetesCluster
    type: string
    default: "ss-stg-01-aks"
  - name: acrName
    type: string
    default: "sdshmctspublic"
  - name: namespace
    type: string
    default: "VH"
  - name: chartName
    type: string
  - name: chartPath
    type: string
  - name: imageTag
    type: string
    default: "$(Build.BuildNumber)"

steps:
  - task: AzureCLI@2
    displayName: 'check creds and AKS merge'
    inputs:
      azureSubscription: "${{ parameters.azureSubscription }}-Video Hearings"
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        az --version
        az account show
        az aks get-credentials --resource-group ${{ parameters.kubernetesCluster }}-rg --name ${{ parameters.kubernetesCluster }}-aks --subscription ${{ parameters.azureSubscription }}

  - task: AzureCLI@2
    displayName: test kubectl and helm from bash
    continueOnError: true 
    inputs:
      azureSubscription: "${{ parameters.azureSubscription }}-Video Hearings"
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        az --version
        az account show
        kubectl get pods -n vh
        helm list --namespace vh

 #- task: AzureCLI@2
 #displayName: 'Deploy ${{ parameters.chartName }} to ${{ parameters.kubernetesCluster }}'
 #inputs:
 #  azureSubscription: '${{ parameters.azureSubscription }}'
 #  scriptType: 'bash'
 #  scriptLocation: 'inlineScript'
 #  inlineScript: |

 #  #connect to aks
 #  az aks get-credentials -g ss-dev-00-rg -n ss-dev-00-aks -s DTS-SHAREDSERVCIES-DEV -a
 #  #configure acr
 #  
 #  az acr login --name $acrName

 #  helm repo add $acrName https://${{ paramters.acrName }}.azurecr.io/helm/v1/repo

 #  helm chart pull ${{ paramters.acrName }}.azurecr.io/

 #  helm upgrade --namespace {{ parameters.namespace }} --create-namespace --install \
 #  --set image.repository=sdshmctspublic/${{ parameters.chartName }} \
 #  --set image.tag=latest \
 #  ${{ parameters.chartName }}  sdshmctspublic/${{ parameters.chartName }} 



  - task: HelmDeploy@0
    displayName: Helm upgrade
    inputs:
      azureSubscriptionEndpoint: 'DTS-SHAREDSERVICES-STG-Video Hearings'
      azureResourceGroup: "ss-stg-01-rg"
      kubernetesCluster: ${{ parameters.kubernetesCluster }}
      command: upgrade
      chartType: filepath
      chartPath: ${{ parameters.chartPath }}/${{ parameters.chartName }}-${{ parameters.imageTag }}.tgz
      releaseName: ${{ parameters.chartName }}
      namespace: ${{ parameters.namespace }}
      install: true
      waitForExecution: false
