parameters:
  - name: helmVersion
    type: string
    default: 'latest'
  - name: acrName
    type: string
  - name: azureSubscription
    type: string
  - name: repositoryName
    type: string
  - name: chartName
    type: string
  - name: chartPath
    type: string
  - name: imageTag
    type: string
    default: "$(Build.BuildNumber)"

steps:

  - task: HelmInstaller@1
    inputs:
      helmVersionToInstall: 'latest'

  - task: AzureCLI@2
    displayName: 'Push ${{ parameters.chartName }} to ${{ parameters.acrName }}'
    inputs:
      azureSubscription: '${{ parameters.azureSubscription }}'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |


        echo "Sign into ${acrName}"
        az acr login --name $acrName

        export HELM_EXPERIMENTAL_OCI=1
        REPOTRIM="$(echo $chartName | sed 's/-//g')"

        echo "Add Helm Repo to ACR"
        helm repo add $acrName https://$acrName.azurecr.io/helm/v1/repo

        cd $chartPath

        echo "Update Dependencys"
        helm dependency update

        echo "Package Chart in ${chartPath}"
        helm package .

        echo "Push $chartName-0.0.1.tgz to ACR with tag $imageTag"
        helm push $chartName-0.0.1.tgz oci://$acrName.azurecr.io/${repositoryName}:$imageTag
    env:
      acrName: "${{ parameters.acrName }}"
      repositoryName: "${{ parameters.repositoryName }}"
      chartName: "${{ parameters.chartName }}"
      chartPath: "${{ parameters.chartName }}"
      imageTag: "${{ parameters.imageTag }}"