parameters:
  - name: helmVersion
    type: string
    default: 'latest'
  - name: azureSubscription
    type: string
    default: ""
  - name: kubernetesCluster
    type: string
    default: "ss-dev-01"
  - name: acrName
    type: string
    default: "sdshmctspublic"
  - name: namespace
    type: string
    default: "vh"
  - name: chartName
    type: string
  - name: fullChartPath
    type: string
  - name: imageTag
    type: string
    default: "$(Build.BuildNumber)"
  - name: valuesFile
    type: string
    default: "values.yaml"

steps:
  - bash: |
        ls -ltr ${{ parameters.fullChartPath }}
        echo "general filecheck"
        ls -ltr . 
        echo ${{ parameters.fullChartPath }}

  - task: HelmDeploy@0
    displayName: Helm upgrade
    inputs:
      connectionType: 'Azure Resource Manager'
      azureSubscriptionEndpoint: '${{ parameters.azureSubscription }}'
      azureResourceGroup: ${{ parameters.kubernetesCluster }}-rg 
      kubernetesCluster: ${{ parameters.kubernetesCluster }}-aks
      command: upgrade
      chartType: filepath
      chartPath: ${{ parameters.fullChartPath }}
      releaseName: ${{ parameters.chartName }}-${{ parameters.imageTag }}
      valueFile: ${{ parameters.chartPath }}/${{ parameters.valuesFile }}
      namespace: ${{ parameters.namespace }}
      install: true
      waitForExecution: false
      useClusterAdmin: true
