parameters:
  - name: helmVersion
    type: string
    default: 'latest'
  - name: azureSubscription
    type: string
    default: ""
  - name: kubernetesCluster
    type: string
    default: "ss-dev-01-aks"
  - name: acrName
    type: string
    default: "sdshmctspublic"
  - name: namespace
    type: string
    default: "vh"
  - name: chartName
    type: string
  - name: chartPath
    type: string
  - name: imageTag
    type: string
    default: "$(Build.BuildNumber)"

steps:

  - task: HelmInstaller@1
    inputs:
      helmVersionToInstall: ${{ parameters.helmVersion }}

  - task: HelmDeploy@0
    displayName: Add ${{ parameters.acrName }}
    inputs:
      useClusterAdmin: true
      connectionType: 'Azure Resource Manager'
      azureSubscription: '${{ parameters.azureSubscription }}'
      azureResourceGroup: ${{ parameters.kubernetesCluster }}-rg 
      kubernetesCluster:  ${{ parameters.kubernetesCluster }}-aks
      command: 'repo'
      arguments: 'add ${{ parameters.acrName }} https://sdshmctspublic.azurecr.io/helm/v1/repo'

  - bash: |
      helm search repo
    displayName: repo search

  - task: HelmDeploy@0
    displayName: Helm upgrade
    inputs:
      connectionType: 'Azure Resource Manager'
      azureSubscriptionEndpoint: '${{ parameters.azureSubscription }}'
      azureResourceGroup: ${{ parameters.kubernetesCluster }}-rg 
      kubernetesCluster: ${{ parameters.kubernetesCluster }}-aks
      command: upgrade
      chartType: name
      chartName: sdshmctspublic/${{ parameters.chartName }}-${{ parameters.imageTag }} #sdshmctspublic/vh-bookings-api 
      releaseName: ${{ parameters.chartName }}-${{ parameters.imageTag }}
      namespace: ${{ parameters.namespace }}
      install: true
      waitForExecution: false
      useClusterAdmin: true
