parameters:
  - name: helmVersion
    type: string
    default: 'latest'
  - name: azureSubscription
    type: string
    default: ""
  - name: kubernetesCluster
    type: string
    default: "ss-dev-01"
  - name: acrName
    type: string
    default: "sdshmctspublic"
  - name: namespace
    type: string
    default: "vh"
  - name: chartName
    type: string
  - name: chartPath
    type: string
  - name: imageTag
    type: string
    default: "$(Build.BuildNumber)"

steps:
  - bash: |
        ls -ltr ${{ parameters.chartPath }}
        echo "general filecheck"
        ls -ltr .
        echo "param check"
        ls -ltr ${{ parameters.imageTag }} 
    

  - task: HelmDeploy@0
    displayName: Helm upgrade
    inputs:
      connectionType: 'Azure Resource Manager'
      azureSubscriptionEndpoint: '${{ parameters.azureSubscription }}'
      azureResourceGroup: ${{ parameters.kubernetesCluster }}-rg 
      kubernetesCluster: ${{ parameters.kubernetesCluster }}-aks
      command: upgrade
      chartType: filepath
      chartName: ${{ parameters.chartPath }}/Chart.yaml
      releaseName: ${{ parameters.chartPath }}-${{ parameters.chartName }}-${{ parameters.imageTag }}.tgz
      valueFile: ${{ parameters.chartPath }}/values.yaml
      namespace: ${{ parameters.namespace }}
      install: true
      waitForExecution: false
      useClusterAdmin: true
