parameters:
  - name: helmVersion
    type: string
    default: 'latest'
  - name: azureSubscription
    type: string
    default: ""
  - name: kubernetesRG
    type: string
  - name: kubernetesCluster
    type: string
    default: "ss-dev-01-aks"
  - name: acrName
    type: string
    default: "sdshmctspublic"
  - name: namespace
    type: string
    default: "vh"
  - name: chartName
    type: string
  - name: chartPath
    type: string
  - name: fullChartName
    type: string
    default: ""
  - name: imageTag
    type: string
    default: "$(Build.BuildNumber)"
  - name: additionalArgs
    type: string
    default: ""

steps:
  - bash: |
        ls -ltr ${{ parameters.chartPath }}/vh-bookings-api
        echo "general filecheck"
        ls -ltr . 
        echo ${{ parameters.chartPath }}
        echo ${{ parameters.fullChartName }}

  - task: HelmDeploy@0
    displayName: Helm upgrade
    inputs:
      connectionType: 'Azure Resource Manager'
      azureSubscriptionEndpoint: '${{ parameters.azureSubscription }}'
      azureResourceGroup: ${{ parameters.kubernetesRG }}
      kubernetesCluster: ${{ parameters.kubernetesCluster }}
      command: upgrade
      chartType: filepath
      chartPath: ${{ parameters.chartPath }}/${{ parameters.fullChartName }}
      releaseName: ${{ parameters.chartName }}-${{ parameters.imageTag }}
      namespace: ${{ parameters.namespace }}
      install: true
      waitForExecution: false
      useClusterAdmin: true
      arguments: ${{ parameters.additionalArgs }}
