parameters:
  - name: helmVersion
    type: string
    default: '2.9.0'
  - name: acrName
    type: string
  - name: azureSubscription
    type: string
  - name: repositoryName
    type: string
  - name: chartName
    type: string
  - name: imageTag
    type: string
    default: "$(Build.BuildNumber)"

steps:

  - task: HelmInstaller@1
    inputs:
      helmVersionToInstall: 'latest'

  - task: AzureCLI@2
    displayName: 'Push ${{ parameters.chartName }} to ${{ parameters.acrName }}'
    inputs:
      azureSubscription: '${{ parameters.azureSubscription }}'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |

        echo "Sign into ${acrName}"
        az acr login --name $acrName
        
        export HELM_EXPERIMENTAL_OCI=1
        REPOTRIM="$(echo $chartName | sed 's/-//g')"

        echo "Add Helm Repo to ACR"
        helm repo add $acrName https://$acrName.azurecr.io/helm/v1/repo

        echo "Package Chart ${chartName}"
        helm package $chartName/charts/$chartName $acrName.azurecr.io/${repositoryName}:$imageTag
        
        echo "Push to ACR with tag $imageTag"
        helm push -n $acrName $acrName.azurecr.io/${repositoryName}:$imageTag 

    env:
      acrName: "${{ parameters.acrName }}"
      repositoryName: "${{ parameters.repositoryName }}"
      chartName: "${{ parameters.chartName }}"
      imageTag: "${{ parameters.imageTag }}"