parameters:
  - name: helmVersion
    type: string
    default: 'latest'
  - name: azureSubscription
    type: string
    default: ""
  - name: kubernetesRG
    type: string
  - name: kubernetesCluster
    type: string
    default: "ss-dev-01-aks"
  - name: acrName
    type: string
    default: "sdshmctspublic"
  - name: namespace
    type: string
    default: "vh"
  - name: chartName
    type: string
  - name: chartPath
    type: string
  - name: fullChartName
    type: string
    default: ""
  - name: imageTag
    type: string
    default: "$(Build.BuildNumber)"
  - name: environment
    type: string
  - name: additionalArgs
    type: string
    default: ""

steps:
  - bash: |
      echo $aksName
      echo $aksRg
      echo $azureSubscription
    env: 
      aksName: ${{ parameters.kubernetesCluster }}
      aksRg: ${{ parameters.kubernetesRG }}
      azureSubscription: ${{ parameters.azureSubscription }}

  - bash: |
      echo "path: ${path}"
      echo "releasename: ${releaseName}"
    env: 
      releaseName: ${{ parameters.chartName }}-${{ parameters.imageTag }}
      path: ${{ parameters.chartPath }}/${{ parameters.fullChartName }}
    displayName: "Helm Details"

  - bash: |
      kubectl describe pod ${{ parameters.chartName }}-${{ parameters.imageTag }}
    displayName: Check pod ${{ parameters.chartName }}-${{ parameters.imageTag }} exists
    #inputs:
    #  connectionType: 'Azure Resource Manager'
    #  azureSubscriptionEndpoint: '${{ parameters.azureSubscription }}'
    #  azureResourceGroup: ${{ parameters.kubernetesRG }}
    #  kubernetesCluster: ${{ parameters.kubernetesCluster }}
    #  command: get
    #  arguments: pods ${{ parameters.chartName }}-${{ parameters.imageTag }} -n ${{ parameters.namespace }}

  - task: HelmDeploy@0
    displayName: Helm Uninstall
    inputs:
      connectionType: 'Azure Resource Manager'
      azureSubscriptionEndpoint: '${{ parameters.azureSubscription }}'
      azureResourceGroup: ${{ parameters.kubernetesRG }}
      kubernetesCluster: ${{ parameters.kubernetesCluster }}
      command: delete
      namespace: ${{ parameters.namespace }}
      useClusterAdmin: true
      arguments: ${{ parameters.chartName }}-${{ parameters.imageTag }}
