parameters:
#GitHub app vars
    - name: privateKeyFileName
      type: string
    - name: appId
      type: string

#GitHub Repo vars
    - name: envValuesTemplatePath
      type: string
    - name: envValuesPath
      type: string
    - name: repositoryName
      type: string
    - name: prTagName
      type: string
    - name: prNumber
      type: string
    - name: chartName
      type: string
    - name: chartPath
      type: string
    - name: releaseName
      type: string

#AKS vars
    - name: acrName
      type: string
    - name: env
      type: string
      default: ""
    - name: subscriptionName
      type: string
    - name: aksResourceGroupName
      type: string
    - name: aksClusterName
      type: string

# DNS vars
    - name: dnsSubscriptionName
      type: string
    - name: dnsResourceGroupName
      type: string
    - name: dnsZone
      type: string
    - name: dnsRecordName
      type: string
    - name: serviceName
      type: string
      default: traefik

steps:
        
    - template: ..\..\Github\get-app-token.yaml
      parameters:
        privateKeyFileName: ${{ parameters.privateKeyFileName }}
        appId: ${{ parameters.appId }}

    - bash: |
        export IMAGE_NAME="${imageName}"
        export SERVICE_FQDN="${fqdn}"
        export RELEASE_NAME="${releaseName}"
        export PR_NUMBER="${prNumber}"
                      
        valuesEnvTemplate="${{ parameters.envValuesTemplatePath }}"
        valuesEnv="${{ parameters.envValuesPath }}"
        
        if test -f "$valuesEnvTemplate"; then
          echo "$valuesEnvTemplate found"
          envsubst < ${valuesEnvTemplate} > ${valuesEnv}
          echo "created $valuesEnv"
          cat $valuesEnv
        else
          echo "No Environment File"
        fi
      displayName: Create Environment Values File
      env:
        imageName: ${{ parameters.acrName }}.azurecr.io/${{ parameters.repositoryName }}:${{ parameters.prTagName }}
        fqdn: ${{ parameters.dnsRecordName }}.${{ parameters.dnsZone }}
        env: ${{ parameters.env }}
        releaseName: "${{ parameters.releaseName }}"
        prNumber: ${{ parameters.prNumber }}
        
    - bash: |
        VERSION=$(cat "${chartPath}/Chart.yaml" | grep ^version | cut -d  ':' -f 2 | tr -d '[:space:]')
        echo "Chart Version: $VERSION"
        echo "##vso[task.setvariable variable=chartVersion;isOutput=true]$VERSION"
      displayName: Get Chart Version
      env:
        chartPath: ${{ parameters.chartPath }}

    - template: ..\..\Azure\Dns\private-dns-add-aks-pr.yaml
      parameters:
        subscriptionName: "${{ parameters.subscriptionName }}"
        aksSubscriptionName: "${{ parameters.subscriptionName }}"
        aksResourceGroupName: "${{ parameters.aksResourceGroupName }}"
        aksClusterName: "${{ parameters.aksClusterName }}"
        dnsSubscriptionName: "${{ parameters.dnsSubscriptionName }}"
        dnsResourceGroupName: "${{ parameters.dnsResourceGroupName }}"
        zoneName: ${{ parameters.dnsZone }}
        recordName: ${{ parameters.dnsRecordName }}
        serviceName: ${{ parameters.serviceName }}

    - template: ..\..\Azure\Common\get-service-connection-details.yaml
      parameters:
        subscriptionName: ${{ parameters.subscriptionName }}

    - template: ..\helm\helm-deploy.yaml
      parameters:
        helmVersion: $(chartVersion)
        azureSubscription: ${{ parameters.subscriptionName }}
        kubernetesRG: "${{ parameters.aksResourceGroupName }}"
        kubernetesCluster: "${{ parameters.aksClusterName }}"
        namespace: "vh"
        releaseName: ${{ parameters.releaseName }}
        chartName: '${{ parameters.chartName }}'
        chartPath: '${{ parameters.chartPath }}'
        imageTag: '${{ parameters.prTagName }}'
        environment: ${{ parameters.env }}
        additionalArgs: "  --wait --set global.enableKeyVaults=true --set global.devMode=true --set global.environment=${{ parameters.env }} --set global.subscriptionId=$(serviceConnection.ARM_SUBSCRIPTION_ID) --set global.tenantId=$(serviceConnection.ARM_TENANT_ID) --timeout 1000s -o json "
