parameters:
  vstsFeedId: '0bb8fdf9-08cc-423c-8a96-81a1e4d65711'
  pool: 'Azure-VSTS-VS2017'
  cleanCheckout: 'false'
  azureSubscription: 'Reform-CFT-VH-Dev'
  buildConfiguration: 'Release'
  sonarCloudProjectKey: ''
  sonarCloudextraProperties: ''
  coverletCoverageExclusions: ''
  integrationTestsAppSettingsTransform: ''
  solutionType: ''
  KeyVaultName: ''
  SecretsFilter: ''
  
jobs:
- job: 
  displayName: 'Build & Test Java Script and .Net Core'
  pool: ${{ parameters.pool }}

  # Reference templae for setting up build tools
  steps:
  - checkout: self  # self represents the repo where the initial Pipelines YAML file was found
    clean: ${{ parameters.cleanCheckout }}  # whether to fetch clean each time

# Runs common steps - gitVersion, Nuget  
  - template: ../templates/common/common.yml


# Restore NuGet packages and build VS solution
  - template: ../templates/vsBuild/dotnetBuild.yml
    parameters:
      buildConfiguration: '${{ parameters.buildConfiguration }}'
      vstsFeedId: '${{ parameters.vstsFeedId }}'

# Publish artifacts
  - template: ../templates/publishArtifacts/publishArtifacts.yml
    parameters:
      dalWorkingDirectory: '${{ parameters.dalWorkingDirectory }}'
      buildConfiguration: '${{ parameters.buildConfiguration }}'
