parameters:
  name: Build & Test - Java & Dotenet
  vstsFeedId: '0bb8fdf9-08cc-423c-8a96-81a1e4d65711'
  pool: Azure-VSTS-VS2017

jobs:
- job: ${{ parameters.name }}
  pool: ${{ parameters.pool }}
  # Reference templae for setting up build tools

