parameters:
  name: 'Build & Test'
  vstsFeedId: '0bb8fdf9-08cc-423c-8a96-81a1e4d65711'
  pool: 'Azure-VSTS-VS2017'
  azureSubscription: 'Reform-CFT-VH-Dev'
  sonarCloudProjectKey: ''
  sonarCloudextraProperties: ''
  buildConfiguration: 'Release'
  solutionType: 'javaDotNetCore'
  KeyVaultName: ''
  
jobs:
- job: 
  displayName: ${{ parameters.name }}
  pool: ${{ parameters.pool }}
  workspace:
    clean: outputs
  # Reference templae for setting up build tools
  steps:
    - template: ../templates/Common/common.yml

  # Performs npm steps - install, build, test, test publishing
    - template: ../templates/npm/npm.yml

  # SonarCloud Prepare step
    - template: ../templates/SonarCloud/SonarCloudPrepare.yml
      parameters:
        sonarCloudProjectKey: ${{ parameters.sonarCloudProjectKey }}
        sonarCloudprojectName: '$(Build.Repository.Name)'
        sonarCloudextraProperties: ${{ parameters.sonarCloudextraProperties }}

  # Restore NuGet packages and build VS solution
    - template: ../templates/VSBuild/VSBuild.yml
      parameters:
        buildConfiguration: '${{ parameters.buildConfiguration }}'

  # Executes unit tests
    - template: ../templates/getSecrets/getSecrets.yml
      parameters:
          azureSubscription: '${{ parameters.azureSubscription }}'
          KeyVaultName: '${{ parameters.KeyVaultName }}'

    # Executes integration tests and publishes results
    - template: ../templates/Tests/runUnitTests.yml
      parameters:
        buildConfiguration: '${{ parameters.buildConfiguration }}'

  # Executes tests and publishes results
    - template: ../templates/Tests/RunTests.yml
      parameters:
        buildConfiguration: '${{ parameters.buildConfiguration }}'

  # Publish artifacts
    - template: ../templates/PublishArtifacts/PublishArtifacts.yml
