parameters:
  - name: packageManagers
    type: object
    default:
     - nuget
  - name: nodeVersion
    type: string
    default: '8.11.4'
  - name: coreProjectPath
    type: string
  - name: nugetConfigPath
    type: string
  - name: integTestProjectPath
    type: string
  - name: testSettings
    type: object
    default: []
  - name: secrets_KeyVault
    type: string
  - name: secrets_Subscription
    type: string

stages:
  - template: ../dotnet-test.yml
    parameters:
      packageManagers: ${{ parameters.packageManagers }}
      nodeVersion:  ${{ parameters.nodeVersion }} 
      secrets_KeyVault: ${{ parameters.secrets_KeyVault }}
      secrets_Subscription: ${{ parameters.secrets_Subscription }}
      baseAgent: windows-latest
      coreProjectPath: ${{ parameters.coreProjectPath }}
      nugetConfigPath: ${{ parameters.nugetConfigPath }}
      integTestProjectPath: ${{ parameters.integTestProjectPath }}
      RunUnitTests: false
      RunIntegrationTests: true
      RunSonarCloud: false
      RunStryker: false
      IntegrationTestSettings:
        - ${{ each setting in parameters.testSettings }}:
          - name: ${{ setting.name }}
            value: ${{ setting.value }}
            secret: ${{ setting.secret }}
            type: ${{ setting.type }}