parameters:
  - name: packageManagers
    type: object
    default:
     - nuget
  - name: nodeVersion
    type: string
    default: '8.11.4'
  - name: coreProjectPath
    type: string
  - name: nugetConfigPath
    type: string
  - name: integTestProjectPath
    type: string
  - name: testSettings
    type: object
    default: []

stages:
  - template: ../dotnet-test.yml
    parameters:
      packageManagers: ${{ parameters.packageManagers }}
      nodeVersion:  ${{ parameters.nodeVersion }}
      testParameters:
        baseAgent: windows-latest
        coreProjectPath: ${{ parameters.coreProjectPath }}
        nugetConfigPath: ${{ parameters.nugetConfigPath }}
        integTestProjectPath: ${{ parameters.integTestProjectPath }}

        secrets_KeyVault: $(pr_Secret_KeyVault)
        secrets_Subscription: $(pr_Secret_Subscription)

        RunUnitTests: false
        RunIntegrationTests: true
        RunSonarCloud: false
        RunStryker: false
        IntegrationTestSettings:
          - ${{ each setting in parameters.testSettings }}:
            - name: ${{ setting.name }}
              value: ${{ setting.value }}
              secret: ${{ setting.secret }}
              type: ${{ setting.type }}