parameters:
  - name: acrName
    type: string
  - name: azureSubscription
    type: string
  - name: imageName
    type: string
  - name: repositoryName
    type: string
  - name: imageTags
    type: object

steps:
  - ${{ each tag in parameters.imageTags }}:

    - powershell: |
        $recievedTag="${{ tag }}"
        Write-Host "Tag before $recievedTag"
        
        $date=$(Get-Date -Format yyyyMMddhhmm);
        $commitId="$(Build.SourceVersion)"
        $shorterCommitId=$commitId.SubString(0,7)

        $newTag= $recievedTag -replace "#{DATETIME}#", $date -replace "#{SHORTCOMMITID}#", $shorterCommitId
        Write-Host "Tag after $newTag"

        Write-Host "##vso[task.setvariable variable=name;isOutput=true]$newTag"
      displayName: Set Tag
      name: tag

    - task: AzureCLI@2
      displayName: 'Push ${{ parameters.imageName }}:${{ tag }} to ${{ parameters.acrName }}'
      inputs:
        azureSubscription: '${{ parameters.azureSubscription }}'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          docker tag $imageName:latest $acrName.azurecr.io/$repositoryName:${tag}
    
          docker images
          az acr login --name sdshmctspublic
          docker push $acrName.azurecr.io/$repositoryName:${tag}
      env:
        acrName: "${{ parameters.acrName }}"
        repositoryName: "${{ parameters.repositoryName }}"
        imageName: "${{ parameters.imageName }}"
        tag: "$(tag.name)"