parameters:
  - name: azureSubscription
    type: string
  - name: acrName
    type: string
  - name: repositoryName
    type: string
  - name: dockerComposeFile
    type: string
    default: "**/docker-compose.yml"
    
steps:
  - task: AzureCLI@2
    displayName: 'Get ID for ${{ parameters.acrName }}'
    inputs:
      azureSubscription: '${{ parameters.azureSubscription }}'
      scriptType: 'pscore'
      scriptLocation: 'inlineScript'
      inlineScript: |
        $acrId=az acr show -n '${{ parameters.acrName }}' --query "id" -o tsv
        echo "##vso[task.setvariable variable=acrId;isOutput=true]$acrId"

  - task: Docker@2
    displayName: 'Login to Azure Container Registry'
    inputs:
      command: 'login'
      containerRegistry: '${{ parameters.acrName }}.azurecr.io'
      azureSubscriptionEndpoint: '${{ parameters.azureSubscription }}'
      azureContainerRegistry: '$(acrId)'

  - task: AzureCLI@2
    displayName: 'Login to Azure'
    inputs:
      azureSubscription: '${{ parameters.azureSubscription }}'
      scriptType: 'ps'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az acr login --name ${{ parameters.acrName }}
