parameters:
  - name: azureSubscription
    type: string
  - name: acrName
    type: string
  - name: repositoryName
    type: string
    
variables:
  ${{ if startsWith(variables['Build.SourceBranch'], 'refs/heads/') }}:
    branchName: $(Build.SourceBranchName)
  ${{ if startsWith(variables['Build.SourceBranch'], 'refs/pull/') }}:
    branchName: $[ replace(variables['System.PullRequest.SourceBranch'], 'refs/heads/', '') ]
    
steps:
  - task: AzureCLI@2
    displayName: 'Get ID for ${{ parameters.acrName }}'
    inputs:
      azureSubscription: '${{ parameters.azureSubscription }}'
      scriptType: 'pscore'
      scriptLocation: 'inlineScript'
      inlineScript: |
        
        $acrId=az acr show -n '${{ parameters.acrName }}' --query "id" -o tsv

        echo "##vso[task.setvariable variable=acrId;isOutput=true]$acrId"
        
  - bash: |
      git checkout $(branchName)
    displayName: Checkout Branch - $(branchName)
      
  - task: DockerCompose@0
    displayName: 'Run a Docker Compose Build'
    inputs:
      azureSubscription: '${{ parameters.azureSubscription }}'
      azureContainerRegistry: '{"loginServer":"${{ parameters.acrName }}.azurecr.io", "id" : "$(acrId)"}'
      projectName: '${{ parameters.acrName }}/${{ parameters.repositoryName }}'
      qualifyImageNames: false
      dockerComposeCommand: build
