parameters:
  - name: acrName
    type: string
  - name: azureSubscription
    type: string
  - name: imageName
    type: string
  - name: repositoryName
    type: string
  - name: imageTags
    type: object

steps:
  - ${{ each tag in parameters.imageTags }}:
    - task: AzureCLI@2
      displayName: 'Push ${{ parameters.imageName }}:${{ tag }} to ${{ parameters.acrName }}'
      inputs:
        azureSubscription: '${{ parameters.azureSubscription }}'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          docker tag $imageName:latest $acrName.azurecr.io/$repositoryName:${tag}
    
          docker images
          az acr login --name sdshmctspublic
          docker push $acrName.azurecr.io/$repositoryName:${tag}
      env:
        acrName: "${{ parameters.acrName }}"
        repositoryName: "${{ parameters.repositoryName }}"
        imageName: "${{ parameters.imageName }}"
        tag: "${{ tag }}"