parameters:
  - name: azureSubscription
    type: string
  - name: acrName
    type: string
  - name: repositoryName
    type: string
  - name: dockerComposeFile
    type: string
    default: "**/docker-compose.yml"
    
steps:
  - task: AzureCLI@2
    displayName: 'Get ID for ${{ parameters.acrName }}'
    inputs:
      azureSubscription: '${{ parameters.azureSubscription }}'
      scriptType: 'pscore'
      scriptLocation: 'inlineScript'
      inlineScript: |
        $acrId=az acr show -n '${{ parameters.acrName }}' --query "id" -o tsv
        echo "##vso[task.setvariable variable=acrId;isOutput=true]$acrId"
  - task: PowerShell@2
    displayName: 'Run Docker Compose Build'
    inputs:
      targetType: 'inline'
      script: |
        param (
            [string]$azureSubscription = '$(azureSubscription)',
            [string]$acrName = '$(acrName)',
            [string]$acrId = '$(acrId)',
            [string]$repositoryName = '$(repositoryName)',
            [string]$dockerComposeFile = '$(dockerComposeFile)'
        )

       # Azure Container Registry login server
       $acrLoginServer = "$acrName.azurecr.io"

       # Login to Azure
       Write-Host "Logging in to Azure..."
       az login --service-principal -u $env:servicePrincipalId -p $env:servicePrincipalKey --tenant $env:tenantId
  
       # Login to Azure Container Registry
       Write-Host "Logging in to Azure Container Registry..."
       az acr login --name $acrName
  
       # Docker Compose build command
       $projectName = "$acrName/$repositoryName"
       $dockerComposeCommand = "build"
  
       # Run Docker Compose build
       Write-Host "Running Docker Compose Build..."
       docker-compose -f $dockerComposeFile $dockerComposeCommand
       Write-Host "Docker Compose Build Completed."
  env:
    servicePrincipalId: $(servicePrincipalId)
    servicePrincipalKey: $(servicePrincipalKey)
    tenantId: $(tenantId)
