parameters:
  - name: azureSubscription
    type: string
  - name: acrName
    type: string
  - name: repositoryName
    type: string
  - name: dockerComposeFile
    type: string
    default: "**/docker-compose.yml"
  - name: containerBuildContext
    type: string
    default: './'
    
steps:
  - task: AzureCLI@2
    displayName: 'Get ID for ${{ parameters.acrName }}'
    inputs:
      azureSubscription: '${{ parameters.azureSubscription }}'
      scriptType: 'pscore'
      scriptLocation: 'inlineScript'
      inlineScript: |
        $acrId=az acr show -n '${{ parameters.acrName }}' --query "id" -o tsv
        echo "##vso[task.setvariable variable=acrId;isOutput=true]$acrId"
      
  - task: Docker@2
    displayName: 'Run a Docker Build'
    inputs:
      azureSubscription: '${{ parameters.azureSubscription }}'
      repository: '${{ parameters.acrName }}/${{ parameters.repositoryName }}'
      qualifyImageNames: false
      buildContext: ${{ parameters.containerBuildContext }}
      #containerRegistry: '{"loginServer":"${{ parameters.acrName }}.azurecr.io", "id" : "$(acrId)"}'
      command: build
