parameters:
  - name: azureSubscription
    type: string
  - name: acrName
    type: string
  - name: repositoryName
    type: string
  - name: dockerComposeFile
    type: string
    default: "**/docker-compose.yml"
    
steps:
  - task: AzureCLI@2
    displayName: 'Get ID for ${{ parameters.acrName }}'
    inputs:
      azureSubscription: '${{ parameters.azureSubscription }}'
      scriptType: 'pscore'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az acr login --name ${{ parameters.acrName }}
        $acrId=az acr show -n '${{ parameters.acrName }}' --query "id" -o tsv
        echo "##vso[task.setvariable variable=acrId;isOutput=true]$acrId"

  - task: PowerShell@2
    displayName: 'Run Docker Compose Build'
    inputs:
      targetType: 'inline'
      script: |
        $dockerComposeFile = '${{ parameters.dockerComposeFile }}'
        $dockerComposeCommand = "up"
        $arguments = "--build"
        $repositoryName = '${{ parameters.repositoryName }}'
        echo "Value 1  ($repositoryName -split '/')[1]"
        echo "Value 2  ($repositoryName -split '/')[2]"
        $projectName = ($repositoryName -split '/')[1]
        
        $command = "docker compose -f $dockerComposeFile -p $projectName $dockerComposeCommand $arguments"
        Write-Host "Executing: $command"
        Invoke-Expression $command
