parameters:
  - name: azureSubscription
    type: string
  - name: acrName
    type: string
  - name: repositoryName
    type: string
    
steps:
  - task: AzureCLI@2
    displayName: 'Get ID for ${{ parameters.acrName }}'
    inputs:
      azureSubscription: '${{ parameters.azureSubscription }}'
      scriptType: 'pscore'
      scriptLocation: 'inlineScript'
      inlineScript: |
        
        $acrId=az acr show -n '${{ parameters.acrName }}' --query "id" -o tsv

        echo "##vso[task.setvariable variable=acrId;isOutput=true]$acrId"
 
  - bash: |
      echo "##[section]checking out branch : $branchName"
      echo  "$(System.PullRequest.SourceBranch)"
      git checkout $branchName
    displayName: Checkout Branch
    env:
      ${{ if startsWith(variables['Build.SourceBranch'], 'refs/heads/') }}:
        branchName: $(Build.SourceBranchName)
      ${{ if startsWith(variables['Build.SourceBranch'], 'refs/pull/') }}:
        branchName: (System.PullRequest.SourceBranch)
      
  - task: DockerCompose@0
    displayName: 'Run a Docker Compose Build'
    inputs:
      azureSubscription: '${{ parameters.azureSubscription }}'
      azureContainerRegistry: '{"loginServer":"${{ parameters.acrName }}.azurecr.io", "id" : "$(acrId)"}'
      projectName: '${{ parameters.acrName }}/${{ parameters.repositoryName }}'
      qualifyImageNames: false
      dockerComposeCommand: build
